#### Numpy Arrays

    1D Array
    2D Array
    3D Array

In [32]:
import numpy as np

# 1D Array
a = [1, 2, 3]
print(type(a))
a1 = np.array(a)
print(type(a1))
print(a1.shape, a1.size, a1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
(3,) 3 int64


In [33]:
import numpy as np

# 2D Array
a_2d = [[1, 2, 3, 4], [4, 5, 6, 4], [7, 8, 9, 4]]
print(type(a_2d))
np_2d = np.array(a_2d)
print(type((np_2d)))
print(np_2d.shape, np_2d.dtype, np_2d.size)

<class 'list'>
<class 'numpy.ndarray'>
(3, 4) int64 12


#### 3D Array

In [34]:
a_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]]
print(type(a_3d))
np_3d = np.array(a_3d)
print(type(np_3d))
print(np_3d.shape, np_3d.size, np_3d.dtype)

class_a_st_ranks = ["a", "b"]
class_a_st_2_ranks = ["c", "d"]
class_b_st_3_ranks = ["e", "f"]
class_b_st_4_ranks = ["g", "h"]
class_a = [class_a_st_ranks, class_a_st_2_ranks]
class_b = [class_b_st_3_ranks, class_b_st_4_ranks]
a_3d_str = [class_a, class_b]
print(type(a_3d_str))
np_3d_str = np.array(a_3d_str)
print(type(np_3d_str))
print(np_3d_str.shape, np_3d_str.size, np_3d_str.dtype)

<class 'list'>
<class 'numpy.ndarray'>
(2, 2, 3) 12 int64
<class 'list'>
<class 'numpy.ndarray'>
(2, 2, 2) 8 <U1


#### List vs Numpy

In [35]:
# On NP Array looping is not required for multiplication
a = [1, 2, 3]
a1 = a * 3
print(a1)
np_a = np.array(a)
np_a1 = np_a * 3
print(np_a1)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [36]:
# On NP Array looping is not required for addition
# list will not support
try:
    np_a = np.array(a)
    np_a1 = np_a + 3
    print(np_a1)
    a = [1, 2, 3]
    a1 = a + 3
    print(a1)
except Exception as ex:
    print(ex)

[4 5 6]
can only concatenate list (not "int") to list


#### Aggregate Functions on Numpy
    Sum
    Mean
    Mode
    Median
    Count
    Std

In [37]:
a = np.array(range(1, 30, 6))
sum_ = np.sum(a)
mean_ = np.mean(a)
max_ = np.max(a)
min_ = np.min(a)
std_ = np.std(a)
count_ = np.size(a)
print(min_, max_, count_, mean_, std_)

1 25 5 13.0 8.48528137423857


In [38]:
a_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]]
np_3d = np.array(a_3d)

axis_0_sum = np_3d.sum(axis=0)
axis_0_sum
axis_1_sum = np_3d.sum(axis=1)
axis_0_sum, axis_1_sum

axis_0_prod = np_3d.prod(axis=0)
axis_0_prod
axis_1_prod = np_3d.prod(axis=1)
axis_0_prod, axis_1_prod

(array([[ 7, 16, 27],
        [ 0,  5, 12]]),
 array([[ 4, 10, 18],
        [ 0,  8, 18]]))

#### Generate Data using Numpy

In [39]:
a = list(range(0, 10, 3))
a
np_a = np.array(a)
np_a
try:
    a = list(range(0.9, 10, 3.9))
    a
except Exception as ex:
    print(ex)

'float' object cannot be interpreted as an integer


In [40]:
np_float_list = np.arange(0.3, 10, 3.9)
np_float_list

array([0.3, 4.2, 8.1])

#### Equally Spaced Values - linspace

In [41]:
c1 = np.linspace(2, 10, 4)
c1

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [42]:
d1 = np.linspace(2, 100, 3)
d1

array([  2.,  51., 100.])

#### Randomly Generated Data

In [43]:
r1 = np.random.random(size=10)
r1

array([0.55670896, 0.95748319, 0.78696737, 0.0592436 , 0.84060728,
       0.00159467, 0.20984275, 0.80132428, 0.86105212, 0.43463268])

In [44]:
r2 = np.random.randint(low=4, high=44, size=10)
r2

array([38, 24, 30, 15, 32, 27, 21, 25, 16, 14], dtype=int32)

In [45]:
d = ["Utkarsh", "Rahul", "Raman"]
d1 = np.array(d)
print(d1, d1.dtype)

['Utkarsh' 'Rahul' 'Raman'] <U7


#### Random normal distribution

In [46]:
np.random.normal(loc=5.5, scale=0.5 / 3)

5.685673533668202

In [47]:
heights = np.random.normal(loc=5.5, scale=0.5 / 3, size=190)
# print(heights)

In [48]:
import seaborn as sns

# sns.histplot(data=heights, kde=True)

In [49]:
heights.mean(), heights.std()

(np.float64(5.503036605974055), np.float64(0.1622378237140906))

# Other mathematical functions can be applied using numpy

In [50]:
a = np.random.randint(low=1, high=50, size=5)
print(a)
a_square = np.square(a)
print(a_square)
a_sqrt = np.sqrt(a)
print(a_sqrt.round(3))

[46 44  6 20 29]
[2116 1936   36  400  841]
[6.782 6.633 2.449 4.472 5.385]


In [51]:
a_sqrt**2

array([46., 44.,  6., 20., 29.])

In [52]:
a_sqrt**3

array([311.98717922, 291.86298155,  14.69693846,  89.4427191 ,
       156.16977941])

In [53]:
np.exp(1)

np.float64(2.718281828459045)

In [54]:
np.exp(a_sqrt)

array([882.12166011, 759.94767385,  11.58243519,  87.54351246,
       218.14605317])

In [55]:
np.log(a_sqrt)

array([1.9143207 , 1.89209482, 0.89587973, 1.49786614, 1.68364791])

#### Calculate sin, cos , tan you require to conver tot radian

In [56]:
# in order to calculate sin, cos , tan you require to conver tot radian
angle_deg = [0, 30, 45, 60, 90]
print(angle_deg)
angle_rad = np.radians(angle_deg)
print(angle_rad.round(3))

[0, 30, 45, 60, 90]
[0.    0.524 0.785 1.047 1.571]


In [57]:
np.sin(angle_rad).round(3)

array([0.   , 0.5  , 0.707, 0.866, 1.   ])

In [58]:
np.cos(angle_rad).round(3)

array([1.   , 0.866, 0.707, 0.5  , 0.   ])

In [59]:
np.tan(angle_rad.round(3))

array([ 0.00000000e+00,  5.77885359e-01,  9.99203990e-01,  1.73126087e+00,
       -4.90982594e+03])

In [60]:
x = [0.1, 0.3, 1, 0.5, 0.8]
rad = np.asin(x)
print(rad.round(3))
deg = np.degrees(rad)
print(deg.round(3))

[0.1   0.305 1.571 0.524 0.927]
[ 5.739 17.458 90.    30.    53.13 ]


In [61]:
np.acos(x), np.atan(x)

(array([1.47062891, 1.26610367, 0.        , 1.04719755, 0.64350111]),
 array([0.09966865, 0.29145679, 0.78539816, 0.46364761, 0.67474094]))